# Generated by Django 3.2 on 2022-11-13 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Product Category',
            },
        ),
        migrations.CreateModel(
            name='Product_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Product_Picture_upload_1', models.ImageField(blank=True, help_text='Insert 500X500 pixel image', null=True, upload_to='img/product/')),
                ('Description', models.TextField(blank=True, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=256, null=True)),
                ('Product_Category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product_category')),
            ],
            options={
                'verbose_name_plural': 'Product Table',
            },
        ),
    ]
