# Generated by Django 3.2 on 2022-11-13 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_table',
            name='Price',
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color', models.CharField(blank=True, max_length=255, null=True)),
                ('Size', models.CharField(blank=True, max_length=255, null=True)),
                ('Embroidery', models.CharField(blank=True, max_length=255, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product_table')),
            ],
        ),
    ]
