# Generated by Django 3.2 on 2022-11-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221113_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='availability',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=256, null=True),
        ),
    ]
