# Generated by Django 3.2 on 2022-11-16 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_attribute_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('availability', models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=256, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product_table')),
            ],
            options={
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='Embroidery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Embroidery', models.CharField(max_length=255)),
                ('Additional_Price', models.CharField(max_length=255)),
                ('availability', models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=256, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product_table')),
            ],
            options={
                'verbose_name_plural': 'Embroidery',
            },
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('availability', models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=256, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product_table')),
            ],
            options={
                'verbose_name_plural': 'Colors',
            },
        ),
    ]
