# Generated by Django 3.2 on 2022-11-16 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_color_embroidery_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
