# Generated by Django 3.2 on 2022-11-18 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='Embroidery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.embroidery'),
        ),
    ]
