# Generated by Django 3.2 on 2022-11-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_cartitem_embroidery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='device_id',
        ),
    ]
