# Generated by Django 3.2 on 2022-11-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_cartitem_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='session_id',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
