# Generated by Django 3.2 on 2022-11-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_cartitem_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='Subtotal_price',
            field=models.IntegerField(default=0),
        ),
    ]
