# Generated by Django 3.2 on 2022-11-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_cartitem_subtotal_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='session_id',
            new_name='Anonymous_User_session_id',
        ),
    ]
